# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.1.0
group=io.github.eoinkanro.mc
java_version=21

# Common
minecraft_version=1.21
mod_name=Lucky Excavation
mod_author=EoinKanro
mod_id=luckyexcavation
license=CC0-1.0
credits=
project_url=https://github.com/EoinKanro/Lucky-Excavation
project_issues_url=https://github.com/EoinKanro/Lucky-Excavation/issues
description=Try your luck! Maybe you will find something interesting during the excavation ;)

minecraft_version_range=[1.21, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.06.23

# Fabric
fabric_version=0.100.1+1.21
fabric_loader_version=0.15.11

# Forge
forge_version=51.0.17
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.0.110-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#libs
cloth_api_version=15.0.127
cloth_api_version_range=[15.0.0,)
lombok_version=1.18.38
kanrommon_version=1.21.0.1
kanrommon_version_range=[1.21.0.1,)
